env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'angular'
plugins:
  - angular
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
